POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 114
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "2",
  "firstName": "John",
  "lastName": "Doe",
  "middleName": "D",
  "emailId": "john.Doe@emal.com"
}

<> 2024-05-22T143845.200.txt

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 114
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "2",
  "firstName": "John",
  "lastName": "Doe",
  "middleName": "D",
  "emailId": "john.Doe@emal.com"
}

<> 2024-05-22T143713.500.json

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 93
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "2",
  "firstName": "John",
  "lastName": "Doe",
  "emailId": "john.Doe@emal.com"
}

<> 2024-05-22T143204.200.txt

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 127
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "2",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.Doe@emal.com",
  "dob": "1990-01-01",
  "age": 30
}

<> 2024-05-22T143127.500.json

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 127
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "2",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.Doe@emal.com",
  "dob": "1990-01-01",
  "age": 30
}

<> 2024-05-22T141620.200.txt

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 127
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "1",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.Doe@emal.com",
  "dob": "1990-01-01",
  "age": 30
}

<> 2024-05-22T141246.200.txt

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 127
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "id": "1",
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.Doe@emal.com",
  "dob": "1990-01-01",
  "age": 30
}

<> 2024-05-22T140808.500.json

###

POST http://localhost:8181/employee
Content-Type: application/json
Content-Length: 114
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.Doe@emal.com",
  "dob": "1990-01-01",
  "age": 30
}

<> 2024-05-22T140509.500.json

###

POST http://localhost:8181/employee?generated-in=IntelliJ IDEA
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0

<> 2024-05-22T140127.400.json

###

POST http://localhost:8181/employee?generated-in=IntelliJ IDEA
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0

<> 2024-05-22T135921.400.json

###

